services:
  bot:
    build:
      context: .
      target: runtime
    environment:
      - GROUP_INVITER_CONFIG=/app/config/config.yaml
    expose:
      - "8000"
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    depends_on:
      - promtail
      - prometheus
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.3
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./monitoring/promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - ./logs:/var/log/group-inviter:ro
      - promtail-positions:/tmp
    depends_on:
      - loki
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.3
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.54.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        CONFIG_FILE=/etc/group-inviter/config.yaml
        TOKEN=$$(awk -F'"' '/bot_token:/ {print $$2; exit}' "$${CONFIG_FILE}")
        CHAT=$$(awk -F': ' '/admin_chat_id:/ {print $$2; exit}' "$${CONFIG_FILE}")
        TEMPLATE=/etc/grafana/provisioning/contact-points/telegram.yaml.tmpl
        OUTPUT=/etc/grafana/provisioning/contact-points/telegram.yaml
        sed "s/__BOT_TOKEN__/$$TOKEN/g; s/__CHAT_ID__/$$CHAT/g" "$${TEMPLATE}" > "$${OUTPUT}"
        exec /run.sh
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./config/config.yaml:/etc/group-inviter/config.yaml:ro
    depends_on:
      - loki
      - prometheus
    restart: unless-stopped

volumes:
  grafana-data:
  loki-data:
  promtail-positions:
  prometheus-data:
