services:
  bot:
    build:
      context: .
      target: runtime
    environment:
      - GROUP_INVITER_CONFIG=/app/config/config.yaml
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    depends_on:
      - promtail
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.3
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./monitoring/promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - ./logs:/var/log/group-inviter:ro
      - promtail-positions:/tmp
    depends_on:
      - loki
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.3
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  grafana-data:
  loki-data:
  promtail-positions:
