apiVersion: 1

policies:
  - orgId: 1
    receiver: grafana-default-email
    routes:
      - receiver: grafana-default-email
        objectMatchers:
          - - severity
            - "="
            - critical
